
// auth types
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCES = 'REGISTER_USER_SUCCES';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCES = "LOGIN_USER_SUCCES";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
export const SET_TOKEN = "SET_TOKEN";

// products
export const FETCH_TYPE_PRODUCTS_REQUEST = "FETCH_TYPE_PRODUCTS_REQUEST";
export const FETCH_TYPE_PRODUCTS_SUCCESS = "FETCH_TYPE_PRODUCTS_SUCCESS";
export const FETCH_TYPE_PRODUCTS_FAILURE = "FETCH_TYPE_PRODUCTS_FAILURE";

export const FETCH_CURRENT_PRODUCT_REQUEST = "FETCH_CURRENT_PRODUCT_REQUEST";
export const FETCH_CURRENT_PRODUCT_SUCCESS = "FETCH_CURRENT_PRODUCT_SUCCESS";
export const FETCH_CURRENT_PRODUCT_FAILURE = "FETCH_CURRENT_PRODUCT_FAILURE";

export const FETCH_HOME_PRODUCTS_REQUEST = "FETCH_HOME_PRODUCTS_REQUEST";
export const FETCH_HOME_PRODUCTS_SUCCESS = "FETCH_HOME_PRODUCTS_SUCCESS";
export const FETCH_HOME_PRODUCTS_FAILURE = "FETCH_HOME_PRODUCTS_FAILURE";

export const FIND_SEARCHED_BOOKS_REQUEST = "FIND_SEARCHED_BOOKS_REQUEST";
export const FIND_SEARCHED_BOOKS_SUCCESS = "FIND_SEARCHED_BOOKS_SUCCESS";
export const FIND_SEARCHED_BOOKS_FAILURE = "FIND_SEARCHED_BOOKS_FAILURE";

// basket products
export const FETCH_BASKET_PRODUCTS_REQUEST = "FETCH_BASKET_PRODUCTS_REQUEST";
export const FETCH_BASKET_PRODUCTS_SUCCESS = "FETCH_BASKET_PRODUCTS_SUCCESS";
export const FETCH_BASKET_PRODUCTS_FAILURE = "FETCH_BASKET_PRODUCTS_FAILURE";

export const REMOVE_BASKET_PRODUCT_REQUEST = "REMOVE_BASKET_PRODUCT_REQUEST";
export const REMOVE_BASKET_PRODUCT_SUCCESS = "REMOVE_BASKET_PRODUCT_SUCCESS";
export const REMOVE_BASKET_PRODUCT_FAILURE = "REMOVE_BASKET_PRODUCT_FAILURE";

export const ADD_PRODUCT_TO_BASKET_REQUEST = "ADD_PRODUCT_TO_BASKET_REQUEST";
export const ADD_PRODUCT_TO_BASKET_SUCCESS = "ADD_PRODUCT_TO_BASKET_SUCCESS";
export const ADD_PRODUCT_TO_BASKET_FAILURE = "ADD_PRODUCT_TO_BASKET_FAILURE";

export const CHANGE_AMOUNT_IN_BASKET_REQUEST = "CHANGE_AMOUNT_IN_BASKET_REQUEST";
export const CHANGE_AMOUNT_IN_BASKET_SUCCESS = "CHANGE_AMOUNT_IN_BASKET_SUCCESS";
export const CHANGE_AMOUNT_IN_BASKET_FAILURE = "CHANGE_AMOUNT_IN_BASKET_FAILURE";

export const REMOVE_ALL_BASKET_PRODUCTS_REQUEST = "REMOVE_ALL_BASKET_PRODUCTS_REQUEST";
export const REMOVE_ALL_BASKET_PRODUCTS_SUCCESS = "REMOVE_ALL_BASKET_PRODUCTS_SUCCESS";
export const REMOVE_ALL_BASKET_PRODUCTS_FAILURE = "REMOVE_ALL_BASKET_PRODUCTS_FAILURE";

export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_SUCCESS = "PAYMENT_SUCCESS";
export const PAYMENT_FAILURE = "PAYMENT_FAILURE";
